"""aws cognito integration

Revision ID: 2178a5a9bb5c
Revises: 834b1a697901
Create Date: 2021-12-26 19:24:00.352539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2178a5a9bb5c'
down_revision = '834b1a697901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('aws_cognito_uid', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_user_aws_cognito_uid'), 'user', ['aws_cognito_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_aws_cognito_uid'), table_name='user')
    op.drop_column('user', 'aws_cognito_uid')
    # ### end Alembic commands ###
